#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
.. module:: zlel_p3.py
    :synopsis: Osagai ez-linealen ebazpena Newton-Raphson bidez.

.. moduleauthor:: Erik Elorduy eta Aitor Serrano
"""

import numpy as np
import sys

if __name__ == "zlel.zlel_p3":
    import zlel.zlel_p1 as zl1
    import zlel.zlel_p2 as zl2
else:
    import zlel_p1 as zl1
    import zlel_p2 as zl2


def diode_NR(I0, nD, Vdj):
    """
    Diodo baten ekuazio esponentziala linealizatzen du puntu zehatz batean, 
    Newton-Raphson metodoaren baliokide diskretua sortuz.
    

    Args:
        I0 (float): Diodoaren saturazio-korrontea.
        nD (float): Diodoaren idealtasun-faktorea.
        Vdj (float): Diodoak aurreko iterazioan zeukan tentsioa (Vd).

    Returns:
        tuple: (gd, Id)
            - gd (float): Baliokide diskretuaren konduktantzia (ukitzailearen malda).
            - Id (float): Baliokide diskretuaren korronte-iturri askea.
    """
    Vt = 8.6173324e-5 * 300 * nD
    exp_val = np.exp(Vdj / Vt)

    gd = -(I0 / Vt) * exp_val
    Id = I0 * (exp_val - 1) + gd * Vdj

    return gd, Id

def q_NR(Ies, Ics, bf, br, Vbe, Vbc):
    """
    Transistore Bipolar (BJT) baten elementu linealak kalkulatzen ditu 
    Ebers-Moll eredua erabiliz. 

    Base-Igorle (BE) eta Base-Kolektore (BC) loturak bi diodo bezala tratatzen ditu, 
    euren arteko irabazi gurutzatuak (alpha_F eta alpha_R) kontuan hartuz.

    Args:
        Ies (float): Igorlearen saturazio-korrontea.
        Ics (float): Kolektorearen saturazio-korrontea.
        bf (float): Aurreranzko korronte-irabazia (beta_F).
        br (float): Atzeranzko korronte-irabazia (beta_R).
        Vbe (float): Base-Igorle tentsioa, aurreko iteraziotik.
        Vbc (float): Base-Kolektore tentsioa, aurreko iteraziotik.

    Returns:
        tuple: (m11, m12, m21, m22, Us_be, Us_bc)
            - m11, m12, m21, m22 (float): Konduktantzia-matrizearen elementuak.
            - Us_be, Us_bc (float): Eredu linealizatuaren korronte-iturri askeak.
    """
    # Alfa parametroak kalkulatu
    af = bf / (bf + 1.0) if bf > 0 else 0.0
    ar = br / (br + 1.0) if br > 0 else 0.0
    
    # Ebers-Moll ereduaren barruko bi diodoak ebaluatu (idealtasun faktorea nD=1.0)
    g_be, I_be_eq = diode_NR(Ies, 1.0, Vbe)
    g_bc, I_bc_eq = diode_NR(Ics, 1.0, Vbc)
    
    # Matrizeen elementuak (Malda konduktantziak)
    m11 = g_be
    m12 = -ar * g_bc
    m21 = -af * g_be
    m22 = g_bc
    
    # Korronte aske baliokideak (Us)
    Us_be = I_be_eq - ar * I_bc_eq
    Us_bc = -af * I_be_eq + I_bc_eq
    
    return m11, m12, m21, m22, Us_be, Us_bc

def solve_nl_circuit(cir_el, cir_nd, cir_val, cir_ctr, branches, Aa, n, b, sweep_el=None, sweep_val=None, t=None):
    """
    Osagai ez-linealak (Diodoak eta Transistoreak) dituzten zirkuituak ebazteko 
    Newton-Raphson iterazio-begizta nagusia.

    Sistema hasierako asmakizun batekin hasten da (0.6V) eta iterazio bakoitzean 
    Tableau matrizea eguneratzen du osagaien baliokide linealak erabiliz. 
    Tentsioen aldaketa tolerantzia baino txikiagoa denean gelditzen da.

    Args:
        cir_el (numpy.ndarray): Elementuen izenak.
        cir_nd (numpy.ndarray): Nodoen matrizea.
        cir_val (numpy.ndarray): Elementuen balioak.
        cir_ctr (numpy.ndarray): Kontrol elementuak.
        branches (list): Adarren hiztegien zerrenda.
        Aa (numpy.ndarray): Intzidentzia matrizea.
        n (int): Nodo kopurua.
        b (int): Adar kopurua.
        sweep_el (str, optional): Ekorketa egiten ari den elementuaren izena (.DC).
        sweep_val (float, optional): Ekorketaren uneko balioa.
        t (float, optional): Denbora balioa (.TR).

    Returns:
        numpy.ndarray: Zirkuituaren azken tentsio eta korronteen bektorea (sol).
    """
    br_map = {br['name'].upper(): i for i, br in enumerate(branches)}
    
    # 1. Hasierako tentsioak (0.6V elementu ez-linealentzat hasten gara)
    v_prev = np.zeros(b)
    for i, el_name in enumerate(cir_el):
        el_type = el_name[0].upper()
        if el_type == 'D':
            v_prev[br_map[el_name.upper()]] = 0.6
        elif el_type == 'Q':
            v_prev[br_map[el_name.upper() + "_BE"]] = 0.6
            v_prev[br_map[el_name.upper() + "_BC"]] = 0.6

    max_iter = 100
    tol = 1e-5

    # 2. Newton-Raphson iterazioak
    for it in range(max_iter):
        # Lineala den zatia eraiki
        M, N, Us = zl2.build_MNUs(cir_el, cir_val, cir_ctr, branches, sweep_el=sweep_el, sweep_val=sweep_val, t=t)
        
        # Ez-lineala den zatia gainidatzi iterazio honetako tentsioekin
        for i, el_name in enumerate(cir_el):
            el_type = el_name[0].upper()
            
            if el_type == 'D':
                j = br_map[el_name.upper()]
                I0, nD = cir_val[i][0], cir_val[i][1]
                Vdj = v_prev[j]
                
                gd, Id = diode_NR(I0, nD, Vdj)
                
                N[j, j] = 1.0
                M[j, j] = gd
                Us[j, 0] = Id
                
            elif el_type == 'Q':
                j_be = br_map[el_name.upper() + "_BE"]
                j_bc = br_map[el_name.upper() + "_BC"]
                
                Ies, Ics, bf, br = cir_val[i][0:4]
                Vbe = v_prev[j_be]
                Vbc = v_prev[j_bc]
                
                # Matrizeen osagaiak kalkulatu
                m11, m12, m21, m22, Us_be, Us_bc = q_NR(Ies, Ics, bf, br, Vbe, Vbc)
                
                # Base-Emitter adarra
                N[j_be, j_be] = 1.0
                M[j_be, j_be] = m11
                M[j_be, j_bc] = m12
                Us[j_be, 0] = Us_be
                
                # Base-Collector adarra
                N[j_bc, j_bc] = 1.0
                M[j_bc, j_be] = m21
                M[j_bc, j_bc] = m22
                Us[j_bc, 0] = Us_bc

        # Sistema ebatzi
        T = zl2.build_tableau(Aa, M, N)
        sol = zl2.solve_tableau(T, Us, n-1)
        
        # Tentsio berriak atera
        v_new = np.zeros(b)
        for j in range(b):
            v_new[j] = sol[n - 1 + j, 0]
            
        # 3. Konbergentzia egiaztatu (Tentsio aldaketa maximoa)
        if np.max(np.abs(v_new - v_prev)) < tol:
            return sol
            
        v_prev = v_new.copy()
        
    print("Errorea: Newton-Raphson metodoak ez du konbergentziarik lortu.")
    sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    else:
        filename = "../cirs/all/2_zlel_1D.cir"
